name: 29Designs Collective
description: The greatest company to ever live
author: 29Designs Collective
author_email: jeff@the29.co
url: http://the29.co
markdown: kramdown
highlighter: rouge

theme: jekyll-theme-minimal

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true